name: Auto Merge

on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
      # 或
      # - uses: actions/checkout@v4
      # - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: 'react-ts,vue-ts'
          github-token: ${{ secrets.GITHUB_TOKEN }}
