name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: 'react-ts,vue-ts'
